//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public static class Extensions
{
	public static Vector2 GetCoordinates<T>(this T[,] array, T searchedItem)
	{
		for (int i = 0; i < array.GetLength(0); i++) 
		{
			for (int j = 0; j < array.GetLength(1); j++) 
			{
				if(array[i,j].Equals(searchedItem))
				{
					return new Vector2(i,j);
				}
			}
		}
		throw new Exception ("item not found");
	}
}

